services:
  db:
    image: postgres:latest
    container_name: qualificationManager3
    environment:
      POSTGRES_USER: mateusz
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: qualification_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: qualificationApp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/qualification_db
      SPRING_DATASOURCE_USERNAME: mateusz
      SPRING_DATASOURCE_PASSWORD: 12345678

volumes:
  db_data: