version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: qualificationManager3
    environment:
      POSTGRES_USER: mateusz
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: qualification_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
