INSERT INTO qualifications (id, name, description) VALUES (4, 'Java', 'Java programming language');
INSERT INTO qualifications (id, name, description) VALUES (5, 'Python', 'Python programming language');
INSERT INTO qualifications (id, name, description) VALUES (6, 'JavaScript', 'JavaScript programming language');
INSERT INTO qualifications (id, name, description) VALUES (7, 'C#', 'C# programming language');
INSERT INTO qualifications (id, name, description) VALUES (8, 'C++', 'C++ programming language');
INSERT INTO qualifications (id, name, description) VALUES (9, 'Ruby', 'Ruby programming language');
INSERT INTO qualifications (id, name, description) VALUES (10, 'PHP', 'PHP programming language');
INSERT INTO qualifications (id, name, description) VALUES (11, 'Swift', 'Swift programming language');
INSERT INTO qualifications (id, name, description) VALUES (12, 'Kotlin', 'Kotlin programming language');
INSERT INTO qualifications (id, name, description) VALUES (13, 'Go', 'Go programming language');
INSERT INTO qualifications (id, name, description) VALUES (14, 'Rust', 'Rust programming language');
INSERT INTO qualifications (id, name, description) VALUES (15, 'TypeScript', 'TypeScript programming language');
INSERT INTO qualifications (id, name, description) VALUES (16, 'SQL', 'Structured Query Language');
INSERT INTO qualifications (id, name, description) VALUES (17, 'HTML', 'HyperText Markup Language');
INSERT INTO qualifications (id, name, description) VALUES (18, 'CSS', 'Cascading Style Sheets');
INSERT INTO qualifications (id, name, description) VALUES (19, 'Bootstrap', 'CSS framework for responsive design');
INSERT INTO qualifications (id, name, description) VALUES (20, 'Spring Boot', 'Java framework for building microservices');
INSERT INTO qualifications (id, name, description) VALUES (21, 'Django', 'Python web framework');
INSERT INTO qualifications (id, name, description) VALUES (22, 'Flask', 'Python micro web framework');
INSERT INTO qualifications (id, name, description) VALUES (23, 'React', 'JavaScript library for building user interfaces');
INSERT INTO qualifications (id, name, description) VALUES (24, 'Angular', 'JavaScript framework for building web applications');
INSERT INTO qualifications (id, name, description) VALUES (25, 'Vue.js', 'JavaScript framework for building user interfaces');
INSERT INTO qualifications (id, name, description) VALUES (26, 'Node.js', 'JavaScript runtime for server-side programming');
INSERT INTO qualifications (id, name, description) VALUES (27, 'Express.js', 'Web application framework for Node.js');
INSERT INTO qualifications (id, name, description) VALUES (28, 'ASP.NET', 'Web framework for .NET');
INSERT INTO qualifications (id, name, description) VALUES (29, 'Laravel', 'PHP web framework');
INSERT INTO qualifications (id, name, description) VALUES (30, 'Symfony', 'PHP web framework');
INSERT INTO qualifications (id, name, description) VALUES (31, 'Ruby on Rails', 'Ruby web framework');
INSERT INTO qualifications (id, name, description) VALUES (32, 'Docker', 'Containerization platform');
INSERT INTO qualifications (id, name, description) VALUES (33, 'Kubernetes', 'Container orchestration platform');
INSERT INTO qualifications (id, name, description) VALUES (34, 'AWS', 'Amazon Web Services');
INSERT INTO qualifications (id, name, description) VALUES (35, 'Azure', 'Microsoft Azure');
INSERT INTO qualifications (id, name, description) VALUES (36, 'GCP', 'Google Cloud Platform');
INSERT INTO qualifications (id, name, description) VALUES (37, 'Terraform', 'Infrastructure as Code tool');
INSERT INTO qualifications (id, name, description) VALUES (38, 'Ansible', 'IT automation tool');
INSERT INTO qualifications (id, name, description) VALUES (39, 'Puppet', 'Configuration management tool');
INSERT INTO qualifications (id, name, description) VALUES (40, 'Chef', 'Configuration management tool');
INSERT INTO qualifications (id, name, description) VALUES (41, 'Jenkins', 'Continuous integration and delivery tool');
INSERT INTO qualifications (id, name, description) VALUES (42, 'Git', 'Version control system');
INSERT INTO qualifications (id, name, description) VALUES (43, 'GitHub', 'Code hosting platform for version control and collaboration');
INSERT INTO qualifications (id, name, description) VALUES (44, 'GitLab', 'Web-based DevOps lifecycle tool');
INSERT INTO qualifications (id, name, description) VALUES (45, 'Bitbucket', 'Git repository management solution');
INSERT INTO qualifications (id, name, description) VALUES (46, 'JIRA', 'Project management tool');
INSERT INTO qualifications (id, name, description) VALUES (47, 'Confluence', 'Collaboration tool');
INSERT INTO qualifications (id, name, description) VALUES (48, 'Slack', 'Collaboration hub');
INSERT INTO qualifications (id, name, description) VALUES (49, 'Trello', 'Project management tool');
INSERT INTO qualifications (id, name, description) VALUES (50, 'Asana', 'Work management platform');